### ISSUE TITLE
進入改裝-他之後會貓掉

### ISSUE THREAD

**Issue by a0902031845** [Gizeta/KanColleCacher#10]
4艦隊沒有問題，但點他之後就有可能立即貓or點一兩頁後貓

**Comment by a0902031845** [comment]
版本是v2.3.0.38 compatible with KCV3.8.2

**Comment by Gizeta** [comment]
暂时没有复现出来，能否提供更详细的信息？

**Comment by a0902031845** [comment]
https://github.com/BossaGroove/KanColleViewer/releases
KCV版本是這個
不用緩存插件就沒事
用插件只清IE緩存會貓
清IE緩存+cache folder裏的檔後沒事
緩存包放回去又開始貓
緩存包已經是某GO最新
WIN7 pro 64bit
