### ISSUE TITLE
如果开启检查资源文件的更新，进入改装选择其它船翻页时会猫掉

### ISSUE THREAD

**Issue by wydy** [Gizeta/KanColleCacher#13]
一直以来都有这个问题，看有人反馈了但是无法复现我来复现一下。请大大修复_(:3」∠)_
手动清理缓存只是为了较快复现会，日常使用经常猫
GIF较大请耐心等待

![image](http://cuntuku.com/images/2016/02/12/GIF.gif)

**Comment by Gizeta** [comment]
方便提供一下KCV的版本及KanColleCacher的版本吗？
主要是想知道KCV是3.x还是4.x。

**Comment by wydy** [comment]
KCV 3.8.2 rev.561
插件版本v2.3.0.38

**Comment by Gizeta** [comment]
或许https://github.com/AtrisMio/KanColleCacher/commit/7d960e0d6c25b64e1ae6b720bfe0b90533fe571a 可以修复（mark一下）
