### ISSUE TITLE
KCV v.4.2.9 下插件不工作

### ISSUE THREAD

**Issue by Explorare** [Gizeta/KanColleCacher#17]
![image](https://cloud.githubusercontent.com/assets/5090766/20468113/ebb65282-afcd-11e6-8849-482f9086033c.png)
设定似乎没错，运行也没有报错，但是缓存和魔改功能无效。
已替换最新版 Nekoxy-fiddler。

**Comment by Gizeta** [comment]
之前旧版kcv是否有这样的情况？kcv4.2.8→4.2.9并没有代理和插件方面的改动。

**Comment by Explorare** [comment]
KCV v4.2.7 替换Nekoxy-fiddler 添加插件后，游戏进入母港底部仍为默认界面，似乎 KCV 无法识别游戏是否成功加载。

**Comment by Gizeta** [comment]
这点我知道，角川又改api了。以前的使用中有没有这种问题？是这次更新之后产生了问题吗？

**Comment by Explorare** [comment]
插件在八月底退坑之前都是正常的，对应的 KCV 版本大概就是 v4.2.7 了。

**Comment by Explorare** [comment]
经过测试，发现是缓存认证的问题。关掉认证 swf 资源后缓存可以无等待加载了。但是魔改依然无法应用。

**Comment by Explorare** [comment]
清了一下魔改缓存后发现魔改正常了，插件工作正常，是我制杖了 ( ﾟ∀。)

**Comment by Gizeta** [comment]
噗。我还没查呢。看了kcv的提交记录就觉得没兼容问题。
不过我感觉缓存的更新机制是有一些问题（不会自动更新缓存），有时间我去查查。

**Comment by Gizeta** [comment]
感觉现在最方便的方式就是下个岛风go缓存包，然后关掉缓存认证。

**Comment by Explorare** [comment]
是的，我用的就是锅 go 的缓存包，但是忘记关缓存认证了，所以用起来卡卡的，就和没开缓存一样。
