### ISSUE TITLE
关于放置界面舰娘语音的缓存读取？

### ISSUE THREAD

**Issue by kikiwalu** [Gizeta/KanColleCacher#19]
我尝试移植了POI的语音字幕到KCV上，换船/补给/修船/战斗/掉落这些场景的语音字幕读取都没太大问题，但是用舰娘的放置语音去关联字幕的时候时灵时不灵。。。我用fiddler监控了下，母港页面点击舰娘的时候没有发出请求，那这个后台缓存调用该怎么监控，真心求教啊

**Comment by Gizeta** [comment]
之前有人做过尝试，IE的缓存机制导致不能捕获请求
http://bbs.ngacn.cc/read.php?tid=10681357

如果需要实现可以试试去参考74eo的实现方法
http://bbs.ngacn.cc/read.php?tid=9050333

**Comment by kikiwalu** [comment]
我终于明白问题出在哪了，TaskRecord里面的GetAndRemove方法默认只保留swf文件，所以除了第一次缓存之后的mp3缓存记录都给删了。。。导致之后的fiddler捕获请求里的mp3没法监控到使用本地文件。
建议在下次更新KanColleCacher的时候把mp3记录也一并保存了
