### ISSUE TITLE
2.2.1.31仍然会有停止响应的问题

### ISSUE THREAD

**Issue by EinhartStratos** [Gizeta/KanColleCacher#3]
玩着玩着就停止响应，错误报告不知道在哪里

**Comment by Gizeta** [comment]
是从v2.1.0.25 final ver.就一直遗留下来的问题吗？
停止响应的时候是什么操作时呢？

**Comment by a0902031845** [comment]
我一直想回報這個問題 從閣下未接手之時已經出現
多數在換裝備換人這種可能要讀取新資料的時間就莫名FC了

**Comment by EinhartStratos** [comment]
换装，入渠，出击，查看一览都有可能
