### ISSUE TITLE
2015/07/17维护后GraphList解析不出期间限定立绘

### ISSUE THREAD

**Issue by Laforeta** [Gizeta/KanColleCacher#4]
维护前后生成GraphList的对比，序号9xx的期间限定立绘解析不到。

https://www.diffchecker.com/rzhbfync

这部分立绘在图鉴里显示正常，api_start2里面也能找到对应的字串，但是因为没有保存之前的返回结果所以无法具体分析变化。

**Comment by Gizeta** [comment]
角川改动了api，节日季节及未使用的数据从api_start2中的api_mst_ship中删除，深海栖舰的属性内容也被删减。

如果要保持原有内容，需要单独留存一份被删除的id信息。
