### ISSUE TITLE
更新缓存文件修改日期时KCV可能失去响应

### ISSUE THREAD

**Issue by Laforeta** [Gizeta/KanColleCacher#5]
使用环境：Windows 7 x64, Windows Vista x64. yuyuvn版KCV r556. 

错误特征：正常游戏过程中突然突然卡死。error2.log里出现如下的错误信息

===================================KAN==COLLE==CACHER======
ERROR   date = 4/07/2015 12:08:32 p.m. +12:00, sender = FiddlerRules, 
        message = 在保存文件修改时间时发生异常。
        exception = System.IO.IOException: 文件“C:\Users\Laforet\Desktop\KanColleViewer ver.3.8.1r555\MyCache\kcs\resources\swf\ships\exedxncqauws.swf”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   在 System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   在 System.IO.FileSystemInfo.set_LastWriteTimeUtc(DateTime value)
   在 System.IO.FileSystemInfo.set_LastWriteTime(DateTime value)
   在 d_f_32.KanColleCacher.FiddlerRules._SaveModifiedTime(String filepath, String gmTime)

重启KCV后一切正常。问题发生无一定规律，但在母港任何一个界面和战斗开始时都可能。频率不高，最频繁时一天可能遇到3-4次。关闭自动更新缓存之后有明显改善但仍然会偶尔发生这个问题。

**Comment by Gizeta** [comment]
我一直是用岛风Go缓存（不检查缓存更新），未遇到过这种问题。

调查中，可能与 #3 是同一问题。
