### ISSUE TITLE
Nekoxy-fiddler会导致kcv获取不了游戏数据吗？

### ISSUE THREAD

**Issue by xiuluo** [Gizeta/KanColleCacher#8]
使用了Nekoxy-fiddler之后，kcv的面板里就不能显示提取到的游戏数据了。面板里一片空白没有任何数据，移除Nekoxy-fiddler之后，就正常了，但是就使用不了KanColleCacher了。
注：Windows 10 x64 10240，kcv v4.1.3，KanColleCacher v2.3.0.38 compatible with KCV4.x

**Comment by xiuluo** [comment]
直连，没有设置代理

**Comment by Gizeta** [comment]
会。Nekoxy-fiddler出错会影响kcv的api抓取。

**Comment by Gizeta** [comment]
Nekoxy-fiddler更新了1.5.1r2。希望能解决这个问题。
[https://github.com/Gizeta/Nekoxy-fiddler/releases/tag/1.5.1r2](https://github.com/Gizeta/Nekoxy-fiddler/releases/tag/1.5.1r2)

**Comment by xiuluo** [comment]
还是无法抓取API

**Comment by Gizeta** [comment]
暂时关闭这条issue，相关内容可以去[https://github.com/Gizeta/Nekoxy-fiddler/issues/1](https://github.com/Gizeta/Nekoxy-fiddler/issues/1)讨论。
