### ISSUE TITLE
KCC功能失效

### ISSUE THREAD

**Issue by Explorare** [Gizeta/KanColleCacher#9]
昨天KCV从3.8.2 rev.1升级至 4.1.3，同时升级KCC插件至最新版，发现poi和Inazuma的魔改立绘失效了，两个版本的KCV分别放在两个目录，但共用一个cache目录，之后切换回3.8.1后发现魔改立绘同样失效了，而魔改文件还在，没有任何变动，清理魔改功能也失效了，于是感觉应该是插件出了问题，KCV显示插件正常加载，但是点清理全部缓存也并不会对缓存目录做出任何修改，这里贴上两个版本的设定

KCV 3.8.1

> [Settings]
> CacheFolder=D:\Games\KanColleViewer ver.3.8\MyCache
> ; 缓存文件夹
> CacheEnabled=1
> ; 启用缓存功能
> HackEnabled=1
> ; 启用Hack规则
> HackTitleEnabled=1
> ; 启用针对TitleCall与WorldName的特殊规则
> HackBookEnabled=1
> ; 启用全图鉴功能
> HackMusicRequestEnabled=1
> ; 启用针对点唱机api请求的特殊规则
> CacheEntryFiles=2
> CachePortFiles=2
> CacheSceneFiles=2
> CacheResourceFiles=2
> CacheSoundFiles=2
> CheckFiles=1
> ; 向服务器发送文件验证请求
> ; 0 - 不验证；1 - 不验证资源SWF文件；2 - 验证所有SWF文件
> ; 验证文件可以保证缓存的游戏文件始终是有效可用的，但因为要与服务器通信所以会比不验证花费更长的加载时间

KCV 4.1.3

> [Settings]
> CacheFolder=D:\Games\KanColleViewer ver.3.8\MyCache
> ; 缓存文件夹
> CacheEnabled=1
> ; 启用缓存功能
> HackEnabled=1
> ; 启用Hack规则
> HackTitleEnabled=1
> ; 启用针对TitleCall与WorldName的特殊规则
> HackBookEnabled=1
> ; 启用全图鉴功能
> HackMusicRequestEnabled=1
> ; 启用针对点唱机api请求的特殊规则
> CacheEntryFiles=2
> CachePortFiles=2
> CacheSceneFiles=2
> CacheResourceFiles=2
> CacheSoundFiles=2
> CheckFiles=1
> ; 向服务器发送文件验证请求
> ; 0 - 不验证；1 - 不验证资源SWF文件；2 - 验证所有SWF文件
> ; 验证文件可以保证缓存的游戏文件始终是有效可用的，但因为要与服务器通信所以会比不验证花费更长的加载时间

系统重启后重试也是不行，没有杀软报错，`<./plugins/>`下的.dll文件全部解除限制了，KCV其他插件包括系统提示均正常。问题第一次出现是在运行了新版KCV和KCC之后，运行之前魔改功能没出问题。

求帮助

**Comment by Gizeta** [comment]
无论是新版还是旧版都不会修改.hack.swf文件。kancollecacher自带的缓存清除功能是(有选择地)清除IE的缓存。建议确认一下IE的缓存是否被清除且flash没有缓存原始立绘，或使用kcv的清除功能并重启kcv。

**Comment by Explorare** [comment]
通过KCC和KCV清理缓存后，关闭重新加载，加载速度明显变慢了，许多立绘需要几秒时间才能加载完，说明KCV用的是IE的缓存而非自定义目录。但KCC加载看起来是正常的，可正常设定，也没有报错，但就是无法应用自定义缓存目录。

**Comment by Gizeta** [comment]
可以尝试一下把缓存目录改到一个空文件夹看是否会自动下载缓存

**Comment by Explorare** [comment]
并不能，更改后关闭KCV，`<KanColleCacher>`中`<CacheFolder>`字段已变为新设定的空白目录，但启动后仍然使用的IE缓存，之前加载过的图片迅速显示，而未加载的图片读取了很久，新设定的目录保持为空。
这个问题可能出在系统层面上，因为我有在移动硬盘上存过一个备份，刚才运行也出现了KCC使用IE缓存而非自定义目录的问题。

**Comment by Explorare** [comment]
更新：刚才使用清理工具清理了系统和IE缓存，重启，运行`4.1.3`发现还是不行，关闭`4.1.3`运行`3.8.1`，发现正确识别了之前的缓存路径，魔改立绘也能显示了，此时再关闭`3.8.1 rev2`运行`4.1.3`，发现同样也能正确识别了，然而最诡异的事情是，此时插件设定的缓存目录为刚才新建的空白目录而非魔改缓存目录，`KanColleCacher.ini`中也是那个空白路径。看来是某个原因导致KCC没能正确应用缓存路径设定，导致缓存和魔改功能失效的。

**Comment by Explorare** [comment]
再更新：刚才点开图鉴发现图片加载的很慢，目测是重新加载中，魔改立绘倒是还能用，但是点选了开全图鉴也没用，非提没有的船显示空白。

**Comment by Gizeta** [comment]
3.8.2应该没有问题。
4.1.3的话收到了很多报告Nekoxy-fiddler导致kcv不能正常抓取api。
目前正在研究。

**Comment by Explorare** [comment]
重试试了下`3.8.1 rev2`，缓存和魔改已经能正常识别了，也可以开全图鉴。另外我没有在`4.1.3`上遇到API数据抓取不全的问题，倒是在新版旧版上遇到装备数据不对的问题，12.7cm连装炮B型改，我有一个，未装配，但`所有装备一览`中却显示4(4)，如果装备给某个DD会显示3(4)并附上DD。

**Comment by Gizeta** [comment]
除了列出来的全图鉴功能和点唱机功能，KanColleCacher并不会去处理api的任何请求。
如果频繁发生这种问题且原版kcv无问题，建议关注一下Nekoxy-fiddler是否有新版release或相关issue。

**Comment by Explorare** [comment]
好的，多谢帮助。目前的结果就是，`4.1.3`可以用魔改了，但是缓存还是用的IE，点图鉴的时候明显有卡顿，然后`4.1.3`下也没法开全图，但因为用处不大所以还能忍。

**Comment by Explorare** [comment]
终于找到问题所在了，原因出在我没能正确安装`Nekoxy-fiddler`，我之前将其放入了`./KCV/Plugins/`下，后来在看`Nekoxy-fiddler` mainpage想到是不是需要直接替换原组件而非插件，就直接覆盖至`./KCV/`下，果然KCC能正常工作了，魔改和全图鉴也可以正常工作了，但是遇到了KCV无法抓取数据的问题，目测是`Nekoxy`的问题，已发[issue](https://github.com/Gizeta/Nekoxy-fiddler/issues/1)
